@startuml 訪問者システムクラス図
skinparam classAttributeIconSize 0
hide circle

class 訪問者システム {
 -ユーザーID
 -パスワード
 -名前
 -学校名
 -所属名
 -メールアドレス
 -電話番号
 -年齢
 -登録した他の訪問者

 +ユーザーID、パスワード、名前、学校名、所属名、メールアドレス、電話番号、年齢を登録する()
 +ユーザーID、パスワード、名前、学校名、所属名、メールアドレス、電話番号、年齢を変更する()
 +ユーザーID、パスワード、名前、学校名、所属名、メールアドレス、電話番号、年齢を削除する()
 +他の訪問者を登録する()
 +他の訪問者情報を参照する()
}

@enduml
