@startuml 訪問者システムドメインモデル図
skinparam componentStyle rectangle

[訪問者システム] o-- [登録]
[訪問者システム] o-- [変更]
[訪問者システム] o-- [削除]
[訪問者システム] o-- [他の訪問者の参照]



[登録] o-- [ユーザーID]
[登録] o-- [パスワード]
[登録] o-- [名前]
[登録] o-- [学校名]
[登録] o-- [所属名]
[登録] o-- [メールアドレス]
[登録] o-- [電話番号]
[登録] o-- [年齢]
[登録] o-- [登録した他の訪問者]

[ログイン情報] o-- [セッショントークン]
[ログイン情報] o-- [リフレッシュトークン]

@enduml