@startuml Robodogクラス図
skinparam classAttributeIconSize 0
hide circle

class RoboDog {
 -myName: String
 -myTime: int
 -goodMorning: String
 -goodAfternoon: String
 -goodNight: String
 -firstValue: int
 -secondValue: int
 -result: String

 +getMyName(): String
 +setMyName(): int
 +setMyTime(): void
 +getMyGreet(): String
 +setTwoValues(): void
 +setAndGetResult(): int
}

@enduml
