@startuml ドメインモデル図
skinparam componentStyle rectangle

[訪問者] o-- [ユーザーID]
[訪問者] o-- [パスワード]
[訪問者] o-- [名前]
[訪問者] o-- [学校名]
[訪問者] o-- [所属名]
[訪問者] o-- [メールアドレス]
[訪問者] o-- [電話番号]
[訪問者] o-- [年齢]

[ログイン情報] o-- [セッショントークン]
[ログイン情報] o-- [リフレッシュトークン]

@enduml